Homepage
Tommymarvel/FIRST-CAPSTONE-PROJECT pull request #1
Opened 2022-07-30 21:55 UTC by Tommymarvel

## YOUTH CONFERENCE 
# This PR consist of HTML file, CSS, and javascript for object

2022-07-30 23:00 UTC, ishimwezachee requested changes
Hi @Tommymarvel , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/DhstvI3zZ598Nb1rFf/giphy-downsized-medium.gif"/>

## Highlights
Linters are passing 👍 
The project is running successfully 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-30 23:00 UTC, ishimwezachee commented on about.html
> +</head>
- [ ]  You should have the same navigation links on your about pages, please fix this issue to go to the next milestone 
![image](https://user-images.githubusercontent.com/43877689/182002629-d29611ca-a90c-473e-9c00-25b1dfa8d3de.png)

2022-07-30 23:00 UTC, ishimwezachee commented on index.html
> +      </section>
- [ ] You should have navigations similar to the one from the designs 
![image](https://user-images.githubusercontent.com/43877689/182002697-68474d00-179c-4c75-ac9d-4d8e3617bb32.png)

2022-07-30 23:00 UTC, ishimwezachee commented on index.html
> +        </div>
You should put you image s in the centers 
![image](https://user-images.githubusercontent.com/43877689/182002785-e2a6b8f3-6ef7-4d5e-8e8c-0399d68fdb8c.png)

2022-08-01 17:22 UTC, RolandM99 requested changes
Hi @Tommymarvel, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [ ] [ OPTIONAL ] Kindly, make sure that you added your `node_modules` directory in your `.gitignore` file. This will help you to ignore all the packages inside the subdirectory `node_modules` and use only the packages you need.
![image](https://user-images.githubusercontent.com/71874425/182202961-0daa63f5-e666-4100-88c8-abacbed99f71.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-01 17:22 UTC, RolandM99 commented on about.html
> +</head>
- [ ] As requested by the previous reviewer, make sure that you're using the same navigation for the desktop version on the about page. It seems that you forgot to implement your menu as expected for the desktop version for `about` page.

2022-08-01 17:22 UTC, RolandM99 commented on index.html
> +      </div>
- [ ] For this project you should follow exactly the original design from Behance. As requested by the previous reviewer, Kindly make sure that your navigation design fit the original design from Behance. here is the original design:
![image](https://user-images.githubusercontent.com/71874425/182206347-d82af688-4dd9-49d7-a1a5-292a90aaca1e.png)

2022-08-01 22:45 UTC, Whoistolu commented on about.html
> +</head>
Well resolved 👍🏽

2022-08-01 22:52 UTC, Whoistolu approved these changes
### Hi @Tommymarvel 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

- [ ]  _Check the inline comments under the review for sections to improve._
- [ ] [OPTIONAL] Kindly ensure that the `node_modules` directory is properly ignored by the `.gitignore` file. The `node_modules` folder is where all packages required by your JavaScript project are downloaded and installed. This folder is commonly excluded from a remote repository because it has a large size and you shouldn’t add code that you didn’t write to the repository.

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 07:40 UTC, merged